name: VERIFY README

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run awesome_bot
        uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow-dupe --allow-redirect README.md